name: CI/CD
on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region ${{ secrets.AWS_REGION }}
        aws s3 sync ./dist/ s3://arn:aws:s3:::hokwe --delete
        
    - name: Set up Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 20.4.0
        
    - name: Build static site
      run: yarn install && yarn build
      
    - name: Deploy static site to S3 bucket
      run: |
        aws s3 sync ./dist/ s3://arn:aws:s3:::hokwe --delete

